#pragma once
#include <QObject>
#include <QTranslator>

// manages the loading and switching of application translations by handling
// the instalation of QTranslator objects on the global QApplication instance
class TranslationManager : public QObject{
    Q_OBJECT
    public:
        TranslationManager(QObject *parent = nullptr);

        // switches the application language based on the provided langCode
        // loads .qm translation file from resources and install it
        // (.qm file is compiled from .ts file from /translation which is generated by the lupdate tool)
        void switchLanguage(const QString &langCode); // langCode - "en" or "pl", by default "en"

    private:
        QTranslator translator;
};

